# Store your API key here for local development
# When deploying to Streamlit Cloud, add this as a secret in the Streamlit dashboard
TOGETHER_API_KEY = "b670710cf7911b7a9a0419dfdfc3551e776646714e44bfe1a24794cbc7bfc2c1" 
